services:
  postgres:
    image: postgres:16-alpine
    container_name: orders_postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7-jammy
    container_name: audit_mongo
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  orders:
    build:
      context: .
      dockerfile: apps/orders/Dockerfile
    container_name: orders_service
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      AUDIT_HOST: audit
    depends_on:
      - postgres
      - mongo

  audit:
    build:
      context: .
      dockerfile: apps/audit/Dockerfile
    container_name: audit_service
    ports:
      - '3001:3001'
      - '4000:4000'
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongo:27017/audit_db
    depends_on:
      - mongo

volumes:
  postgres_data:
  mongo_data:
